modLoader="javafml"
loaderVersion="[47,)"
license="GNU Lesser General Public License version 3 (LGPLv3)"

[[mods]]
modId="manors_bounty"
version="0.2.10"
displayName="Manor's Bounty"
displayURL="http://manors_bounty.net/"
logoFile="logo.png"
credits="Created using mod maker MCreator."
authors="DJInfinite"
description="Manor\u2018s Bounty"

[[dependencies.manors_bounty]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.manors_bounty]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.manors_bounty]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.manors_bounty]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration